spring:
  application:
    name: api
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: Authorization
  secret:
    key: EIJXbcvMJcZRXQ8EhR4x5Cs3YVBd+B77wVnZv0U0Aac=
    token-validity-in-seconds: 604800

naver:
  clova:
    apiKey : NTA0MjU2MWZlZTcxNDJiY71zbl8q71f1sERnVRwzt+RZzWbe5i+VpjnKxSOpoXuV
    apiGatewayKey : UDVKcQUFxEzQ5JnZdVZfrGw9pIcljFyiWz7y9rKg
    clientid: owkwud0ncz
    secretkey: f2BmL2UpjJAx756MSQAJpXfO5wE2kcoPchgK8mfE

#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG